# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
#title:      Agnese Poikāne | par grāmatām, datiem un sabiedrību
#title:       ![image-alumni](/images/posts/rakstam/ap_logo _zils 2-02.svg)
title:       Agnese Poikāne </br> par grāmatām, datiem un sociālajām problēmām

email:       'agnesepoikane@inbox.lv'
#description: 'Аналитика данных, социология и методы исследования'
baseurl:     '' # The subpath of your site, e.g. /blog
url:         'https://blog.agnesepoikane.com/' # The base hostname & protocol for your site

github:      'https://github.com/agnesepoikane'
linkedin:    'https://www.linkedin.com/in/agnese-poikane/'
facebook:    'https://www.facebook.com/agnese.poikane/'
instagram:   'https://www.instagram.com/poikaneagnese/'
#goodreads:   'https://www.goodreads.com/user/show/22833723-agnese' 


markdown:  kramdown
permalink: pretty
paginate:  10

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-commonmark
  - jemoji

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

default_lang: 'lv'
languages:
  ru:
    country: ru # defines country code for flag icon
    title: Читать по-русски
  en:
    country: gb
    title: Read it in english
  lv:
    country: lv
    title: Lasīt latviski

#default_lang: 'ru'
#languages:
#  ru:
#    country: ru # defines country code for flag icon
#    title: Читать по-русски
#  en:
#    country: gb
#    title: Read it in english
#  lv:
#    country: lv
#    title: Read it in latvian
