# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:       Agnese Poikane | Data Analyst & Sociologist
email:       'agnesepoikane.inbox.lv'
description: 'Аналитика данных, социология и методы исследования'
baseurl:     '' # The subpath of your site, e.g. /blog
url:         'https://type-jekyll.aspirethemes.com/' # The base hostname & protocol for your site
#twitter:     ''
github:      'https://github.com/puchokagnese'
linkedin:    'https://www.linkedin.com/in/agnese-poikane-pucoka/'
facebook:    'https://www.facebook.com/agnese.poikane/'
instagram:   'https://www.instagram.com/poikaneagnese/'


markdown:  kramdown
permalink: pretty
paginate:  10

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
